### ISSUE TITLE
Firmware suggestion: PSX, Saturn/Genesis, N64, Wii

### ISSUE THREAD

**Issue by exyoh0** [misteraddons/Reflex-Adapt#28]
Since we're getting other combos with the big 3 of this console gen, tacking Wii on for Classic Mini convenience would be ideal.

**Comment by misteraddons** [comment]
Done, thanks for the suggestion!

https://github.com/misteraddons/Reflex-Adapt/commit/e12ed6b41f6947e3fed2f356be8e03ddafeb7ff9
