### ISSUE TITLE
Default mappings for Wii Classic controller mix up menu A and B

### ISSUE THREAD

**Issue by Sheeg** [misteraddons/Reflex-Adapt#33]
With the default menu mappings B gets mapped to A/OK for MiSTer menus, and A gets mapped to B/back - I would expect this to be the other way around like it is for the SNES controller, as per Nintendo convention.

**Comment by misteraddons** [comment]
Should be fixed with the updated mapping that I just pushed. Will you test it (manual download since the updater repo doesn't overwrite existing mappings)?

**Comment by Sheeg** [comment]
Thanks, yeah that worked perfectly!
