### ISSUE TITLE
Possible to support 2P Wii / SNES Classic controllers?

### ISSUE THREAD

**Issue by pete-woods** [misteraddons/Reflex-Adapt#56]
Hi, is it possible in theory to add support for 2P SNES classic controllers?

Like is the underlying hardware fully taken up by handling one controller? Or can that be changed?

Thanks!

**Comment by misteraddons** [comment]
Hey, thanks for the suggestion. Sadly, it’s a hardware limitation. The
microcontroller isn’t fast enough to decode 2 Wii classic controllers in
parallel :(

**Comment by pete-woods** [comment]
Oh well! Thanks for the info, before I tried to spend time writing a patch to do that!
